version: "3.9"

services:
  web:
    build: .
    container_name: django_app
    command: ["python", "manage.py", "runserver", "127.0.0.1:8000"]
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    expose:
      - "8000"
