# Generated by Django 4.2 on 2023-04-17 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cpu', models.CharField(max_length=100)),
                ('gpu', models.CharField(max_length=100)),
                ('ram', models.CharField(max_length=100)),
                ('psu', models.CharField(max_length=100)),
                ('cpu_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('gpu_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('ram_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('psu_price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
