# Generated by Django 4.2 on 2023-04-17 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScriptLanguagesApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pc',
            name='cpu',
            field=models.CharField(max_length=100, verbose_name='Procesor'),
        ),
        migrations.AlterField(
            model_name='pc',
            name='cpu_price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Cena procesora'),
        ),
        migrations.AlterField(
            model_name='pc',
            name='gpu',
            field=models.CharField(max_length=100, verbose_name='Karta graficzna'),
        ),
        migrations.AlterField(
            model_name='pc',
            name='gpu_price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Cena karty graficznej'),
        ),
        migrations.AlterField(
            model_name='pc',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nazwa zestawu'),
        ),
        migrations.AlterField(
            model_name='pc',
            name='psu',
            field=models.CharField(max_length=100, verbose_name='Zasilacz'),
        ),
        migrations.AlterField(
            model_name='pc',
            name='psu_price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Cena zasilacza'),
        ),
        migrations.AlterField(
            model_name='pc',
            name='ram',
            field=models.CharField(max_length=100, verbose_name='Pamięć RAM'),
        ),
        migrations.AlterField(
            model_name='pc',
            name='ram_price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Cena pamięci RAM'),
        ),
    ]
