# Generated by Django 4.2 on 2023-05-07 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScriptLanguagesApp', '0004_pcrating_pc_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='pc',
            name='average_rating',
            field=models.FloatField(default=0, editable=False, verbose_name='Średnia ocena'),
        ),
    ]
